### PR TITLE
[#4] Escaping special TeamCity patterns

### PR DESCRIPTION
**Pull request by krizalys**
Escaping special TeamCity patterns as defined at https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity

This should solve #4.

### CODE REVIEW

**Comment by krizalys** [comment]
@leafle Any update on this?

**Review by leafle — COMMENTED** [review]
Thanks for helping with this issue and I'm sorry I'm not super attentive right now.

I'm a little unclear about whether we should escape \uNNNN or 0xNNNN. My reading of the link you provided suggests the former but this change escapes the latter.

Were able to test this change, I unfortunately can't test against teamcity at the moment.

**Comment by krizalys** [comment]
Thanks for the review, you seem to be right about Unicode escaping, I'll adjust the PR accordingly.

As for testing, I was able to test **some** cases (quotes) using a real TeamCity setup and it was working.

Do you plan to add automated testing capabilities to this project? If you have no preference, I can add dependencies to mocha + expect.js and add unit tests for this change.

**Comment by krizalys** [comment]
Hi @leafle, there were indeed a few replacements which were not working as documented. I fixed them.

Also, I added a mini-test suite in a separate PR proving that the `#escape()` function now works as documented: https://github.com/leafle/newman-reporter-teamcity/pull/9.

**Review by leafle — APPROVED** [review]
Looks great! Thanks for this fix.

**Pull request merged**
