### PR TITLE
add installation and usage instructions

### LINKED ISSUE #1: add README instructions
any usage instructions would be very handy

### PR DESCRIPTION
**Pull request by natelowry**
fixes https://github.com/leafle/newman-reporter-teamcity/issues/1

### CODE REVIEW

**Comment by JeffLoo-ong** [comment]
Hey Nate!

I was just working with this and have some extra notes to add specifically for Windows users I encountered. I'll just make a list here that you can maybe add to your Pull request.

1. Install steps 'npm install -g newman' and 'npm install -g newman-teamcity-reporter' do not work in the build steps.  **I had to manually go onto the server that would be my agent for teamcity and enter those commands into the command prompt**

2. In my Custom Script build step I had to modify the run command to something like this:
C:\Users\\[YourUserProfile]\AppData\Roaming\npm\newman run **"**https://www.getpostman.com/collections/[YourPostmanCollectionIdHere]**"** -x --delay-request 10 -r teamcity  **Notice the quotes around the link.** 

3. I had to use C:\Users\\[YourUserProfile]\AppData\Roaming\npm\newman since I kept getting the error _'newman' is not recognized as an internal or external command_

Really glad you added in these usage notes, I hope they get merged into the main repo soon!

**Comment by natelowry** [comment]
Hi @JeffLoo-ong, thanks for the notes.  I'll add a note for 1 and fix the quotes for 2. 

I _think_ 3 is usually due to npm not being on the path and/or not installing newman globally.  See [this SO thread](https://stackoverflow.com/questions/30710550/node-js-npm-modules-installed-but-command-not-recognized) and see if that helps.  I think that's specific to your environment (I've run into that a lot).

**Review by leafle — APPROVED** [review]
I'm sorry I've been so neglectful. Thank you for writing these docs up, they were sorely needed.

**Comment by natelowry** [comment]
No problem!  Thanks for the project! 🤜 :boom: 🤛

**Pull request merged**
